### ISSUE TITLE
Not working in Ubuntu

### ISSUE THREAD

**Issue by ragundo** [cvuchener/dfhack-qt#1]
Hi
Tried your plugin. Compiled and installed
![Screenshot_20190318_224840](https://user-images.githubusercontent.com/9405614/54566107-399b1200-49d0-11e9-939c-f10537b6d8a7.png)
But it says QApplication not started.
stderr.log and stdout.log don't say anything interesting.

Is there a way to debug this?.
I'm really, really interested in make this work

**Comment by cvuchener** [comment]
The command for enabling the plugin is `enable qapplication`.

**Comment by ragundo** [comment]
OK. That was it
It's working flawlessly.
Excelent work by the way
