### ISSUE TITLE
Working in ubuntu :)

### ISSUE THREAD

**Issue by ragundo** [cvuchener/dfhack-qt#2]
Working beautifully.

![dwarf_explorer](https://user-images.githubusercontent.com/9405614/55352869-2dc84900-54c2-11e9-8732-447bbdd22aea.png)

I need to do a lot of testing and try it in Windows, but this is promising.

Thanks for your work

**Comment by cvuchener** [comment]
X11 or wayland? Are you using a SDL compatibility library (sdlcl or libsdl12-compat)? a modified libgraphics.so?

**Comment by ragundo** [comment]
· X11
· SDL, I installed libsdl1.2-dev, as the instructions for compiling DFHack state
· libgraphics.so is the one that comes with the LNP for linux.

One question. I can see that the qapplication can load Qt resources using qresource::registerresource.
Can I do the same inside the widget app?. It would be ideal if I could add the .qrc file to CMakeList.txt but I don't know how to do that.

**Comment by cvuchener** [comment]
QResource::registerResource is for external *binary* resources (.rcc files, not .qrc). I wanted to use that for icon themes on non-Linux platforms, but I did not manage to make it work on Windows yet.

For adding internal resources, [qt5_add_resources](https://doc.qt.io/qt-5/cmake-manual.html#qt5core-macros) should work, but I did not test it.
