### ISSUE TITLE
using pluginupdate

### ISSUE THREAD

**Issue by ragundo** [cvuchener/dfhack-qt#7]
Hi there.

Short story.For my plugin, I need to hook up on DFHack onpluginupdate signal.

Long history. I want to change the Dwarf Fortress window to a specific coordinate every time the user selects a structure that contains a df::coord field.
If you call the dfhack methods to do that, it will not work because a CoreSuspender is already active, so the call doesn't have any effect until the CoreSuspender is resumed and the render thread updates the screen.

I've tried to call the dfhack methods, resume the CoreSuspender and sleep my thread a few milliseconds for render to update. Then I suspend again. This sometimes work, sometimes crashes.
The solution is to set the parameters, resume the CoreSuspender and use onpluginupdate to do the work

The problem is that this signal should be implemented in your main.cpp (where the Qt application is created), but I can't figure out how to implement that method using data from my plugin. 
I tried to use global variables, but the linker complains.

How to do that?. Is it possible to implement some signal slot between your main.cpp and my plugin?

Thanks in advance

**Comment by cvuchener** [comment]
First, try to not hold on the CoreSuspender if you want the user to be able to do anything else than using your window. Interacting with DF from another thread when it wasn't made for this is hard. Not really much simpler than making a external application, but you have the advantage of sharing the DFHack structures.

If you want to send signals from DFHack callbacks to your Qt objects, you can check the EventProxy class from my example (https://github.com/cvuchener/dfhack-qt/tree/labors2/labors). [EventProxy](https://github.com/cvuchener/dfhack-qt/blob/labors2/labors/EventProxy.h) is an empty QObject that only has only signals, it is shared between the main windows (as a shared_ptr) and a global from main.cpp (as a weak_ptr). The QObject must be created on the Qt thread ([the main window factory in this example](https://github.com/cvuchener/dfhack-qt/blob/labors2/labors/main.cpp#L46-L50)), not in the DFHack thread.

If you want to do the reverse (sending events from your Qt objects to DFHack callbacks), you will need to implement your own event queue. Don't use Qt event queues in DFHack thread.

**Comment by ragundo** [comment]
Ok
